//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoIPApp.Modules.Chat.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ISessionInitializerService")]
    public interface ISessionInitializerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionInitializerService/Call", ReplyAction="http://tempuri.org/ISessionInitializerService/CallResponse")]
        void Call(int friendID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionInitializerService/Call", ReplyAction="http://tempuri.org/ISessionInitializerService/CallResponse")]
        System.Threading.Tasks.Task CallAsync(int friendID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISessionInitializerServiceChannel : VoIPApp.Modules.Chat.ServiceReference.ISessionInitializerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionInitializerServiceClient : System.ServiceModel.ClientBase<VoIPApp.Modules.Chat.ServiceReference.ISessionInitializerService>, VoIPApp.Modules.Chat.ServiceReference.ISessionInitializerService {
        
        public SessionInitializerServiceClient() {
        }
        
        public SessionInitializerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionInitializerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionInitializerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionInitializerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Call(int friendID) {
            base.Channel.Call(friendID);
        }
        
        public System.Threading.Tasks.Task CallAsync(int friendID) {
            return base.Channel.CallAsync(friendID);
        }
    }
}
