//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoIPApp.Modules.Chat.VoiceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VoiceServiceReference.IVoiceService")]
    public interface IVoiceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoiceService/Call", ReplyAction="http://tempuri.org/IVoiceService/CallResponse")]
        int Call(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoiceService/Call", ReplyAction="http://tempuri.org/IVoiceService/CallResponse")]
        System.Threading.Tasks.Task<int> CallAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoiceServiceChannel : VoIPApp.Modules.Chat.VoiceServiceReference.IVoiceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoiceServiceClient : System.ServiceModel.ClientBase<VoIPApp.Modules.Chat.VoiceServiceReference.IVoiceService>, VoIPApp.Modules.Chat.VoiceServiceReference.IVoiceService {
        
        public VoiceServiceClient() {
        }
        
        public VoiceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoiceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Call(int value) {
            return base.Channel.Call(value);
        }
        
        public System.Threading.Tasks.Task<int> CallAsync(int value) {
            return base.Channel.CallAsync(value);
        }
    }
}
